language: php

matrix:
  include:
    - php: 7.2
      env: deps=low
    - php: 7.3
    - php: 7.4
    - php: 8.0

install:
  - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else composer install; fi

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email:
    - jakub+ci@zalas.pl
  irc: "irc.freenode.org#symfony-pl"
