language: php

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email:
    - jakub+ci@zalas.pl
  irc: "irc.freenode.org#symfony-pl"
