language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: bin/phpspec run --no-ansi --format=dot

notifications:
  email:
    - jakub+ci@zalas.pl
    - cakper+ci@gmail.com
  irc: "irc.freenode.org#symfony-pl"
